<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DocumentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('documents')->delete();

        \DB::table('documents')->insert(array (
            0 =>
            array (
                'id' => 1,
                'title' => 'Nam eos nemo ratione perferendis et iste.',
                'slug' => 'nam-eos-nemo-ratione-perferendis-et-iste',
                'tags' => '["qui","aperiam"]',
                'categories' => '["voluptatum","doloribus"]',
                'number' => '0',
                'version' => '8',
                'departments' => '[1,3,2]',
                'effective_date' => '2002-01-29',
                'expired_date' => '1974-03-27',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            1 =>
            array (
                'id' => 2,
                'title' => 'Voluptatem vel quam enim occaecati unde.',
                'slug' => 'voluptatem-vel-quam-enim-occaecati-unde',
                'tags' => '["a","nihil"]',
                'categories' => '["aut","voluptatibus"]',
                'number' => '5',
                'version' => '2',
                'departments' => '[1,3,2]',
                'effective_date' => '1990-07-07',
                'expired_date' => '1983-05-27',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            2 =>
            array (
                'id' => 3,
                'title' => 'Labore ipsum sed qui quis.',
                'slug' => 'labore-ipsum-sed-qui-quis',
                'tags' => '["qui","qui"]',
                'categories' => '["reiciendis","modi"]',
                'number' => '8',
                'version' => '7',
                'departments' => '[1,3,2]',
                'effective_date' => '2019-02-22',
                'expired_date' => '2005-08-23',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            3 =>
            array (
                'id' => 4,
                'title' => 'Minus sed beatae quidem id perspiciatis animi.',
                'slug' => 'minus-sed-beatae-quidem-id-perspiciatis-animi',
                'tags' => '["est","sit"]',
                'categories' => '["qui","fugit"]',
                'number' => '5',
                'version' => '1',
                'departments' => '[1,3,2]',
                'effective_date' => '2008-04-23',
                'expired_date' => '2015-09-22',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            4 =>
            array (
                'id' => 5,
                'title' => 'Et molestiae quasi debitis deleniti aspernatur in incidunt amet.',
                'slug' => 'et-molestiae-quasi-debitis-deleniti-aspernatur-in-incidunt-amet',
                'tags' => '["eaque","dignissimos"]',
                'categories' => '["nihil","nam"]',
                'number' => '9',
                'version' => '7',
                'departments' => '[1,3,2]',
                'effective_date' => '2017-11-13',
                'expired_date' => '1989-07-23',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            5 =>
            array (
                'id' => 6,
                'title' => 'Est pariatur in assumenda sint ut.',
                'slug' => 'est-pariatur-in-assumenda-sint-ut',
                'tags' => '["ipsam","possimus"]',
                'categories' => '["praesentium","a"]',
                'number' => '5',
                'version' => '0',
                'departments' => '[1,3,2]',
                'effective_date' => '1997-02-03',
                'expired_date' => '2008-12-27',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            6 =>
            array (
                'id' => 7,
                'title' => 'Eos molestiae deserunt in in veniam.',
                'slug' => 'eos-molestiae-deserunt-in-in-veniam',
                'tags' => '["a","praesentium"]',
                'categories' => '["et","aut"]',
                'number' => '5',
                'version' => '6',
                'departments' => '[1,3,2]',
                'effective_date' => '2007-04-02',
                'expired_date' => '1975-06-24',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            7 =>
            array (
                'id' => 8,
                'title' => 'Ut velit neque blanditiis rerum qui assumenda.',
                'slug' => 'ut-velit-neque-blanditiis-rerum-qui-assumenda',
                'tags' => '["aperiam","ut"]',
                'categories' => '["labore","doloremque"]',
                'number' => '0',
                'version' => '5',
                'departments' => '[1,3,2]',
                'effective_date' => '2009-12-08',
                'expired_date' => '2008-01-17',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            8 =>
            array (
                'id' => 9,
                'title' => 'Neque voluptas et culpa asperiores sed veritatis.',
                'slug' => 'neque-voluptas-et-culpa-asperiores-sed-veritatis',
                'tags' => '["impedit","sunt"]',
                'categories' => '["aut","ut"]',
                'number' => '9',
                'version' => '1',
                'departments' => '[1,3,2]',
                'effective_date' => '2012-09-17',
                'expired_date' => '1987-09-23',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            9 =>
            array (
                'id' => 10,
                'title' => 'Suscipit ipsam quo et vel placeat.',
                'slug' => 'suscipit-ipsam-quo-et-vel-placeat',
                'tags' => '["nihil","repudiandae"]',
                'categories' => '["quasi","est"]',
                'number' => '4',
                'version' => '4',
                'departments' => '[1,3,2]',
                'effective_date' => '2018-05-21',
                'expired_date' => '2015-01-27',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            10 =>
            array (
                'id' => 11,
                'title' => 'Repellendus voluptates aut excepturi.',
                'slug' => 'repellendus-voluptates-aut-excepturi',
                'tags' => '["adipisci","voluptas"]',
                'categories' => '["ad","labore"]',
                'number' => '8',
                'version' => '2',
                'departments' => '[1,3,2]',
                'effective_date' => '1973-05-08',
                'expired_date' => '2009-06-11',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            11 =>
            array (
                'id' => 13,
                'title' => 'Ea sed natus ut mollitia.',
                'slug' => 'ea-sed-natus-ut-mollitia',
                'tags' => '["ad","quia"]',
                'categories' => '["rerum","vero"]',
                'number' => '7',
                'version' => '1',
                'departments' => '[1,3,2]',
                'effective_date' => '1975-03-07',
                'expired_date' => '1991-06-02',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            12 =>
            array (
                'id' => 14,
                'title' => 'Distinctio perferendis est voluptatibus.',
                'slug' => 'distinctio-perferendis-est-voluptatibus',
                'tags' => '["aliquid","magnam"]',
                'categories' => '["enim","expedita"]',
                'number' => '3',
                'version' => '7',
                'departments' => '[1,3,2]',
                'effective_date' => '1971-08-13',
                'expired_date' => '2018-01-09',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            13 =>
            array (
                'id' => 15,
                'title' => 'Quibusdam ipsa et praesentium blanditiis nihil eos.',
                'slug' => 'quibusdam-ipsa-et-praesentium-blanditiis-nihil-eos',
                'tags' => '["dolor","dolor"]',
                'categories' => '["est","voluptas"]',
                'number' => '0',
                'version' => '5',
                'departments' => '[1,3,2]',
                'effective_date' => '2015-12-26',
                'expired_date' => '2012-09-03',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            14 =>
            array (
                'id' => 16,
                'title' => 'Repellendus autem sapiente facilis autem corrupti perferendis ad nemo.',
                'slug' => 'repellendus-autem-sapiente-facilis-autem-corrupti-perferendis-ad-nemo',
                'tags' => '["et","eum"]',
                'categories' => '["est","quaerat"]',
                'number' => '4',
                'version' => '7',
                'departments' => '[1,3,2]',
                'effective_date' => '2018-07-29',
                'expired_date' => '1985-06-23',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            15 =>
            array (
                'id' => 17,
                'title' => 'Doloribus id facilis accusantium fugiat.',
                'slug' => 'doloribus-id-facilis-accusantium-fugiat',
                'tags' => '["consequuntur","repudiandae"]',
                'categories' => '["voluptatem","veritatis"]',
                'number' => '1',
                'version' => '5',
                'departments' => '[1,3,2]',
                'effective_date' => '2001-10-12',
                'expired_date' => '1976-11-16',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            16 =>
            array (
                'id' => 18,
                'title' => 'Dolores omnis in unde reprehenderit.',
                'slug' => 'dolores-omnis-in-unde-reprehenderit',
                'tags' => '["qui","cupiditate"]',
                'categories' => '["eaque","ducimus"]',
                'number' => '4',
                'version' => '1',
                'departments' => '[1,3,2]',
                'effective_date' => '2001-01-03',
                'expired_date' => '1994-04-11',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            17 =>
            array (
                'id' => 19,
                'title' => 'Et modi ad fugiat tenetur dicta ea.',
                'slug' => 'et-modi-ad-fugiat-tenetur-dicta-ea',
                'tags' => '["soluta","pariatur"]',
                'categories' => '["et","sit"]',
                'number' => '3',
                'version' => '9',
                'departments' => '[1,3,2]',
                'effective_date' => '1987-10-05',
                'expired_date' => '2016-09-06',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            18 =>
            array (
                'id' => 20,
                'title' => 'Voluptatem exercitationem accusantium qui voluptas ut autem minus.',
                'slug' => 'voluptatem-exercitationem-accusantium-qui-voluptas-ut-autem-minus',
                'tags' => '["quidem","aut"]',
                'categories' => '["inventore","beatae"]',
                'number' => '9',
                'version' => '1',
                'departments' => '[1,3,2]',
                'effective_date' => '1989-03-07',
                'expired_date' => '1984-09-05',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 10:22:55',
            ),
            19 =>
            array (
                'id' => 12,
                'title' => 'Aut cumque sapiente nemo ab porro ut eum.',
                'slug' => 'aut-cumque-sapiente-nemo-ab-porro-ut-eum',
                'tags' => '["molestiae","consectetur"]',
                'categories' => '["blanditiis","atque"]',
                'number' => '1',
                'version' => '8',
                'departments' => '[1,3,2]',
                'effective_date' => '2006-12-30',
                'expired_date' => '2005-05-13',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => 70,
                'created_at' => '2021-03-03 10:22:55',
                'updated_at' => '2021-03-03 14:26:37',
            ),
        ));


    }
}
