<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DocumentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('documents')->delete();
        
        \DB::table('documents')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Quia totam et quidem earum.',
                'slug' => 'quia-totam-et-quidem-earum',
                'tags' => '["sit","amet"]',
                'categories' => '["et","amet"]',
                'number' => '6',
                'version' => '1',
                'departments' => '[1,3,2]',
                'effective_date' => '2019-12-07',
                'expired_date' => '1999-05-30',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Accusantium atque dolorem pariatur.',
                'slug' => 'accusantium-atque-dolorem-pariatur',
                'tags' => '["est","temporibus"]',
                'categories' => '["fugiat","odio"]',
                'number' => '4',
                'version' => '6',
                'departments' => '[1,3,2]',
                'effective_date' => '1988-09-21',
                'expired_date' => '1975-12-22',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Atque ipsa quia nihil nisi ea ea.',
                'slug' => 'atque-ipsa-quia-nihil-nisi-ea-ea',
                'tags' => '["molestias","et"]',
                'categories' => '["saepe","sint"]',
                'number' => '2',
                'version' => '2',
                'departments' => '[1,3,2]',
                'effective_date' => '1984-09-16',
                'expired_date' => '2007-09-27',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Pariatur corrupti ipsam voluptatum rerum voluptas reiciendis magnam minus.',
                'slug' => 'pariatur-corrupti-ipsam-voluptatum-rerum-voluptas-reiciendis-magnam-minus',
                'tags' => '["rerum","debitis"]',
                'categories' => '["maxime","sed"]',
                'number' => '9',
                'version' => '4',
                'departments' => '[1,3,2]',
                'effective_date' => '1970-10-18',
                'expired_date' => '1981-12-17',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Sit aliquam rerum voluptates sint et quibusdam harum.',
                'slug' => 'sit-aliquam-rerum-voluptates-sint-et-quibusdam-harum',
                'tags' => '["quis","consequatur"]',
                'categories' => '["perspiciatis","minus"]',
                'number' => '5',
                'version' => '0',
                'departments' => '[1,3,2]',
                'effective_date' => '1994-08-26',
                'expired_date' => '2004-02-25',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Qui eum sit fugiat debitis dolorem est nihil.',
                'slug' => 'qui-eum-sit-fugiat-debitis-dolorem-est-nihil',
                'tags' => '["natus","voluptatem"]',
                'categories' => '["quas","ad"]',
                'number' => '7',
                'version' => '8',
                'departments' => '[1,3,2]',
                'effective_date' => '2015-02-19',
                'expired_date' => '1978-10-24',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Et voluptates ullam reiciendis officia.',
                'slug' => 'et-voluptates-ullam-reiciendis-officia',
                'tags' => '["et","esse"]',
                'categories' => '["quae","magni"]',
                'number' => '0',
                'version' => '7',
                'departments' => '[1,3,2]',
                'effective_date' => '1975-08-23',
                'expired_date' => '1973-01-29',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Eum magni iure vel quos et veniam praesentium sunt.',
                'slug' => 'eum-magni-iure-vel-quos-et-veniam-praesentium-sunt',
                'tags' => '["nulla","hic"]',
                'categories' => '["neque","eum"]',
                'number' => '0',
                'version' => '4',
                'departments' => '[1,3,2]',
                'effective_date' => '1970-06-23',
                'expired_date' => '1978-06-07',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Adipisci aperiam sint aut possimus explicabo non.',
                'slug' => 'adipisci-aperiam-sint-aut-possimus-explicabo-non',
                'tags' => '["unde","nulla"]',
                'categories' => '["autem","molestias"]',
                'number' => '7',
                'version' => '0',
                'departments' => '[1,3,2]',
                'effective_date' => '1989-04-06',
                'expired_date' => '2004-05-09',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Est ullam ut dolorum voluptate et aut amet.',
                'slug' => 'est-ullam-ut-dolorum-voluptate-et-aut-amet',
                'tags' => '["excepturi","ad"]',
                'categories' => '["est","eaque"]',
                'number' => '3',
                'version' => '2',
                'departments' => '[1,3,2]',
                'effective_date' => '1988-10-09',
                'expired_date' => '1988-03-21',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Voluptatum ipsum consectetur dolorem recusandae quis.',
                'slug' => 'voluptatum-ipsum-consectetur-dolorem-recusandae-quis',
                'tags' => '["nobis","neque"]',
                'categories' => '["minima","molestiae"]',
                'number' => '2',
                'version' => '4',
                'departments' => '[1,3,2]',
                'effective_date' => '1976-04-20',
                'expired_date' => '1994-01-11',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Quas sed et et incidunt vel.',
                'slug' => 'quas-sed-et-et-incidunt-vel',
                'tags' => '["est","cupiditate"]',
                'categories' => '["consequatur","aut"]',
                'number' => '0',
                'version' => '7',
                'departments' => '[1,3,2]',
                'effective_date' => '2007-03-04',
                'expired_date' => '1994-05-09',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Aut cum dolor nisi voluptatem minus eius.',
                'slug' => 'aut-cum-dolor-nisi-voluptatem-minus-eius',
                'tags' => '["veritatis","vitae"]',
                'categories' => '["soluta","doloremque"]',
                'number' => '4',
                'version' => '8',
                'departments' => '[1,3,2]',
                'effective_date' => '1979-11-29',
                'expired_date' => '1971-03-07',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'Illum corrupti ullam maxime dolorum.',
                'slug' => 'illum-corrupti-ullam-maxime-dolorum',
                'tags' => '["et","ipsum"]',
                'categories' => '["perferendis","excepturi"]',
                'number' => '8',
                'version' => '9',
                'departments' => '[1,3,2]',
                'effective_date' => '2018-06-24',
                'expired_date' => '1973-06-11',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Culpa totam provident dolor et dolore.',
                'slug' => 'culpa-totam-provident-dolor-et-dolore',
                'tags' => '["omnis","dolor"]',
                'categories' => '["est","laborum"]',
                'number' => '9',
                'version' => '9',
                'departments' => '[1,3,2]',
                'effective_date' => '2010-12-19',
                'expired_date' => '1982-10-21',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Eum quam aut iste sed nisi tenetur saepe.',
                'slug' => 'eum-quam-aut-iste-sed-nisi-tenetur-saepe',
                'tags' => '["id","non"]',
                'categories' => '["qui","quidem"]',
                'number' => '7',
                'version' => '2',
                'departments' => '[1,3,2]',
                'effective_date' => '1982-05-12',
                'expired_date' => '2013-08-29',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Reprehenderit illo inventore sed impedit odit impedit.',
                'slug' => 'reprehenderit-illo-inventore-sed-impedit-odit-impedit',
                'tags' => '["sed","architecto"]',
                'categories' => '["quidem","consectetur"]',
                'number' => '9',
                'version' => '5',
                'departments' => '[1,3,2]',
                'effective_date' => '1998-11-15',
                'expired_date' => '2020-11-22',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Libero in aut temporibus officiis vel.',
                'slug' => 'libero-in-aut-temporibus-officiis-vel',
                'tags' => '["labore","nulla"]',
                'categories' => '["laboriosam","ducimus"]',
                'number' => '1',
                'version' => '4',
                'departments' => '[1,3,2]',
                'effective_date' => '1994-09-19',
                'expired_date' => '2016-10-18',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Dolores et voluptates id veniam ex vel.',
                'slug' => 'dolores-et-voluptates-id-veniam-ex-vel',
                'tags' => '["est","in"]',
                'categories' => '["aut","ratione"]',
                'number' => '2',
                'version' => '7',
                'departments' => '[1,3,2]',
                'effective_date' => '1983-12-20',
                'expired_date' => '1976-12-22',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 0,
                'is_public' => true,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Adipisci ut quidem qui provident quaerat.',
                'slug' => 'adipisci-ut-quidem-qui-provident-quaerat',
                'tags' => '["voluptatem","cum"]',
                'categories' => '["ratione","quibusdam"]',
                'number' => '9',
                'version' => '9',
                'departments' => '[1,3,2]',
                'effective_date' => '2015-02-08',
                'expired_date' => '1974-10-30',
                'owner_id' => 1,
                'favourites' => '[3,2,4]',
                'type' => 1,
                'is_public' => false,
                'status' => 1,
                'exam_minimum_score' => NULL,
                'exam_max_duration' => NULL,
                'created_at' => '2021-03-05 16:22:35',
                'updated_at' => '2021-03-05 16:22:35',
            ),
        ));
        
        
    }
}