<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 2,
                'name' => 'Cristal O\'Conner MD',
                'email' => 'lhomenick@example.com',
                'email_verified_at' => '2021-03-03 10:22:23',
                'position' => 'Plating Machine Operator',
                'department_id' => 7,
                'password' => '$2y$10$PaqvQBldJXMGWKF/emrpy.Dzg/UeFmAhcJJ/PI.DPjzmHBjI98OK2',
                'remember_token' => 'sKvHfU1nfI',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            1 => 
            array (
                'id' => 4,
                'name' => 'Shana Abbott',
                'email' => 'isobel.stark@example.net',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Insurance Appraiser',
                'department_id' => 10,
                'password' => '$2y$10$ZDN/0KOv2rqjqavl/86muOUK5DxZBVdhL600bKIM/Elicc528zly.',
                'remember_token' => 'Q5nubnJcJb',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            2 => 
            array (
                'id' => 5,
                'name' => 'Prof. Maybell Balistreri MD',
                'email' => 'jo52@example.net',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Ophthalmic Laboratory Technician',
                'department_id' => 5,
                'password' => '$2y$10$6.kZmN5m6cK2myEvfUq4SOue89Ahx3ff80aTAcHK8Gu5zdL4KJ.7C',
                'remember_token' => 'oVGkTov54d',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            3 => 
            array (
                'id' => 6,
                'name' => 'Jarrod Funk',
                'email' => 'reinhold30@example.com',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Tire Changer',
                'department_id' => 7,
                'password' => '$2y$10$Rae0OqWBDp0/s0.61bAB8.M0VMcCX2T8tD4YZrjArTCKh1LVsoc1u',
                'remember_token' => 'TyImmtUscD',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            4 => 
            array (
                'id' => 7,
                'name' => 'Fleta Schinner',
                'email' => 'franco.lubowitz@example.org',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Emergency Management Specialist',
                'department_id' => 10,
                'password' => '$2y$10$mcmD03xyTFWgD2YVb.nbOO.yh8LWOLbHoZoVO9Y/yLd6ObCRC6t5C',
                'remember_token' => 'uu8iPP1GVU',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'name' => 'Catharine Ryan',
                'email' => 'heller.geovanni@example.org',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Plastic Molding Machine Operator',
                'department_id' => 1,
                'password' => '$2y$10$OwRqrLvI1VoCECzYvSHYaOV.yBn51agLhw9t3W4QyWpEaU./szDSW',
                'remember_token' => 'V2zDSqEcoB',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'name' => 'Miss Krista Kassulke',
                'email' => 'xschultz@example.org',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Parts Salesperson',
                'department_id' => 8,
                'password' => '$2y$10$/K4haw.sZNHxk5/QcMwKCuBB4AiFB.90ZBzx9t1choY.bNvODnQW2',
                'remember_token' => 'NWgshGR8gf',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'name' => 'Prof. Crystel Ankunding',
                'email' => 'xtoy@example.com',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'File Clerk',
                'department_id' => 7,
                'password' => '$2y$10$wp7wMhZBJB3As5/AaEMyM.k6MzMmwAHRWGDwFWDilBnSalW9GMSey',
                'remember_token' => 'aeW95Fy96I',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'name' => 'Dr. Lemuel Harber',
                'email' => 'kstoltenberg@example.org',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Able Seamen',
                'department_id' => 2,
                'password' => '$2y$10$2wkSVISmAt6yZ1S34eFvGuSpWn0q3V.cfToh8WPF/LlI3SqaGTx4O',
                'remember_token' => 'jrOPoLqJJ5',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            9 => 
            array (
                'id' => 12,
                'name' => 'Bart Spinka Jr.',
                'email' => 'tara61@example.org',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Commercial Diver',
                'department_id' => 4,
                'password' => '$2y$10$CeZN/.EdwjHVEhsudQWN8uWN8tDrtOK8gm43l94GtGvdZOYYYj//O',
                'remember_token' => 'iOMdp3SYK9',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            10 => 
            array (
                'id' => 13,
                'name' => 'Emmitt Dare',
                'email' => 'donnelly.gwen@example.org',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Short Order Cook',
                'department_id' => 1,
                'password' => '$2y$10$ZE3NPfUtjElHko2RMnFFGONUZZM8NZWwitkXHzfWc96HzoXKQU4RK',
                'remember_token' => 'ESeFf686Pj',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'name' => 'Agnes Rogahn',
                'email' => 'demarco.hermann@example.org',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Legislator',
                'department_id' => 5,
                'password' => '$2y$10$AlgmwdzGPyRrLRrQIWWy2uzXw4GwJLiftzMxC0SHUuZS3E5KWOO3i',
                'remember_token' => 'mnW7B03Onp',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            12 => 
            array (
                'id' => 15,
                'name' => 'Dusty Crist',
                'email' => 'stokes.federico@example.org',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Cartoonist',
                'department_id' => 7,
                'password' => '$2y$10$grSDmyJR6jFDmss3qV871e44.81G9.9DEL5wTAjq8ut/0nod2kR.i',
                'remember_token' => 'idZBYfctCn',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'name' => 'Stevie Hayes',
                'email' => 'upton.rigoberto@example.net',
                'email_verified_at' => '2021-03-03 10:22:25',
                'position' => 'Textile Cutting Machine Operator',
                'department_id' => 7,
                'password' => '$2y$10$yfwhO3bZAkCFSbmRYZLZ2ua4yAB6CnR3jzNqjmSUJ/xyZZG13mfbm',
                'remember_token' => 'E6P1cCR5ve',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            14 => 
            array (
                'id' => 17,
                'name' => 'Freddy Veum',
                'email' => 'clementina48@example.org',
                'email_verified_at' => '2021-03-03 10:22:25',
                'position' => 'Special Forces Officer',
                'department_id' => 5,
                'password' => '$2y$10$t.NK3Kdb7O9BauU7dkd48.bqgc/l75J2V1ZCLO6k4OLk/e2UJwv0C',
                'remember_token' => 'mhV0tXZEON',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            15 => 
            array (
                'id' => 18,
                'name' => 'Dr. Jack Bogisich MD',
                'email' => 'fkling@example.org',
                'email_verified_at' => '2021-03-03 10:22:25',
                'position' => 'Mechanical Door Repairer',
                'department_id' => 4,
                'password' => '$2y$10$FNnLcz6gVpk1k/qwDoxwo.g0vcdVE7mikSSTJpKg/dK9nu2XOqfv.',
                'remember_token' => 'M9byaWhuoc',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            16 => 
            array (
                'id' => 19,
                'name' => 'Prof. Nicholaus Tremblay',
                'email' => 'alexane25@example.com',
                'email_verified_at' => '2021-03-03 10:22:25',
                'position' => 'Janitor',
                'department_id' => 7,
                'password' => '$2y$10$3ikwR3M6PlB.IRdrkaESX.byKz4HS28PA3cjueQ9f5kaytwn0Hdp2',
                'remember_token' => 'AuyJY5QEJV',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            17 => 
            array (
                'id' => 20,
                'name' => 'Vicenta Bednar',
                'email' => 'homenick.hyman@example.org',
                'email_verified_at' => '2021-03-03 10:22:25',
                'position' => 'Food Servers',
                'department_id' => 9,
                'password' => '$2y$10$H5wukPfsnrRE6eTXCKeTvOYg9TRMjZJPSh2XMZnSdwDJtMHwaxvHS',
                'remember_token' => 'KEtYa9eHth',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-03 10:22:25',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            18 => 
            array (
                'id' => 1,
                'name' => 'Admin',
                'email' => 'admin@mail.com',
                'email_verified_at' => '2021-03-03 10:20:00',
                'position' => 'System App',
                'department_id' => 1,
                'password' => '$2y$10$jhXrEQFZ5j3pebGKwauDyeMgn2UGNvAjauGZhP8PzIr2exgGhUxsS',
                'remember_token' => 'zGe9flhgVZiI3uE8UB2Xk0rTTSo8mEJHh759YQKOZgbSv9bRH3W9xbHKaQud',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:20:00',
                'updated_at' => '2021-03-03 10:20:00',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
            19 => 
            array (
                'id' => 3,
                'name' => 'Prof. Malinda Turcotte DVM',
                'email' => 'assignee@mail.com',
                'email_verified_at' => '2021-03-03 10:22:24',
                'position' => 'Animal Care Workers',
                'department_id' => 4,
                'password' => '$2y$10$0S9xULcgOU/QuAAIDEuftOLNTLM4Gml3Yf5LWXemUauKRSN91DK9u',
                'remember_token' => '8dBigwECP0',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'status' => true,
                'created_at' => '2021-03-03 10:22:25',
                'updated_at' => '2021-03-04 13:24:33',
                'deleted_at' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
            ),
        ));
        
        
    }
}